### ISSUE TITLE
Void ESP doesn't work if they aren't 2 blocks of air above him

### ISSUE THREAD

**Issue by Natan515** [lambda-client/lambda-legacy#88] opened 2021-05-16 14:07 UTC
![2021-05-16_17 03 42](https://user-images.githubusercontent.com/66911017/118400126-006e9300-b669-11eb-85c1-bb87425985d9.png)

**Comment by ToxicAven** [comment] 2021-05-17 18:21
Working as intended, as you cannot enter the void there without a pearl.

**Comment by Natan515** [comment] 2021-05-17 21:50
We'll it would be nice to have an option there and it can be set on default to what it is currently.

**Comment by ToxicAven** [comment] 2021-05-18 00:21
![6uk44mmk1y](https://user-images.githubusercontent.com/53945697/118572033-71877680-b74d-11eb-9562-8c71e926a56d.gif)

**Comment by Natan515** [comment] 2021-05-18 06:54
Nice!

**Comment by ToxicAven** [comment] 2021-05-18 11:40
PR merged, this can be closed.

**Closed as completed** 2021-05-18 11:53 UTC
Labels: bug
